FROM python:3.13

EXPOSE 8001

WORKDIR /workspace/backend

RUN pip install --upgrade pip

COPY ./backend/requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt\
    && rm -rf /tmp/pip-tmp